// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoPoy.Api.Data;

namespace PoPoy.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CheckoutCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<double>("PayPalPayment")
                        .HasColumnType("float");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("orderReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Giày Adidas",
                            SortOrder = 1,
                            Status = 1,
                            Url = "adidas-shoes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Giày Jordan",
                            SortOrder = 1,
                            Status = 1,
                            Url = "jordan-shoes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Giày Nike",
                            SortOrder = 1,
                            Status = 1,
                            Url = "nike-shoes"
                        });
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(Max)");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("data")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DataUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.OrderDetails", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("OrderIdFromOrder")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("OrderIdFromOrder");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CheckoutCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("ReviewAverage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 946, DateTimeKind.Local).AddTicks(6505),
                            Description = "ADIDAS ALPHABOOST “CORE BLACK”",
                            OriginalPrice = 2150000m,
                            Price = 2150000m,
                            ReviewAverage = 0m,
                            Title = "ADIDAS ALPHABOOST “CORE BLACK”",
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6604),
                            Description = "ADIDAS NMD R1 SERIAL PACK METAL GREY",
                            OriginalPrice = 1650000m,
                            Price = 1650000m,
                            ReviewAverage = 0m,
                            Title = "ADIDAS NMD R1 SERIAL PACK METAL GREY",
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6625),
                            Description = "ADIDAS SEAN WOTHERSPOON X SUPERSTAR ‘SUPER EARTH – BLACK’",
                            OriginalPrice = 3250000m,
                            Price = 3250000m,
                            ReviewAverage = 0m,
                            Title = "ADIDAS SEAN WOTHERSPOON X SUPERSTAR ‘SUPER EARTH – BLACK’",
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6627),
                            Description = "ADIDAS SUPERSTAR OG ‘VINTAGE WHITE’",
                            OriginalPrice = 1650000m,
                            Price = 1650000m,
                            ReviewAverage = 0m,
                            Title = "ADIDAS SUPERSTAR OG ‘VINTAGE WHITE’",
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6629),
                            Description = "ADIDAS NMD R1 TOKYO DRAGON",
                            OriginalPrice = 1850000m,
                            Price = 1850000m,
                            ReviewAverage = 0m,
                            Title = "ADIDAS NMD R1 TOKYO DRAGON",
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6631),
                            Description = "ADIDAS ULTRA BOOST 20 NASA CLOUD WHITE ",
                            OriginalPrice = 2550000m,
                            Price = 2550000m,
                            ReviewAverage = 0m,
                            Title = "ADIDAS ULTRA BOOST 20 NASA CLOUD WHITE ",
                            Views = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6728),
                            Description = "AIR JORDAN 1 HIGH ‘BORDEAUX’",
                            OriginalPrice = 6100000m,
                            Price = 6100000m,
                            ReviewAverage = 0m,
                            Title = "AIR JORDAN 1 HIGH ‘BORDEAUX’",
                            Views = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6733),
                            Description = "AIR JORDAN 1 HIGH OG “BUBBLE GUM”",
                            OriginalPrice = 6450000m,
                            Price = 6450000m,
                            ReviewAverage = 0m,
                            Title = "AIR JORDAN 1 HIGH OG “BUBBLE GUM”",
                            Views = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6735),
                            Description = "AIR JORDAN 1 HIGH RETRO ‘HERITAGE’ GS ",
                            OriginalPrice = 4850000m,
                            Price = 4850000m,
                            ReviewAverage = 0m,
                            Title = "AIR JORDAN 1 HIGH RETRO ‘HERITAGE’ GS ",
                            Views = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6736),
                            Description = "AIR JORDAN 1 HIGH ZOOM ‘CANYON RUST’ ",
                            OriginalPrice = 5550000m,
                            Price = 5550000m,
                            ReviewAverage = 0m,
                            Title = "AIR JORDAN 1 HIGH ZOOM ‘CANYON RUST’ ",
                            Views = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6739),
                            Description = "AIR JORDAN 1 LOW GS TRIPLE WHITE ",
                            OriginalPrice = 3850000m,
                            Price = 3850000m,
                            ReviewAverage = 0m,
                            Title = "AIR JORDAN 1 LOW GS TRIPLE WHITE ",
                            Views = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6740),
                            Description = "AIR JORDAN 1 LOW GS RUSH BLUE BRILL ",
                            OriginalPrice = 4350000m,
                            Price = 4350000m,
                            ReviewAverage = 0m,
                            Title = "AIR JORDAN 1 LOW GS RUSH BLUE BRILL ",
                            Views = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6742),
                            Description = "CR7 X AIR MAX 97 GS ‘PORTUGAL PATCHWORK’ ",
                            OriginalPrice = 4300000m,
                            Price = 4300000m,
                            ReviewAverage = 0m,
                            Title = "CR7 X AIR MAX 97 GS ‘PORTUGAL PATCHWORK’ ",
                            Views = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6745),
                            Description = "GIÀY NIKE DUNK LOW DISRUPT 2 ‘MALACHITE’ ",
                            OriginalPrice = 4850000m,
                            Price = 4850000m,
                            ReviewAverage = 0m,
                            Title = "GIÀY NIKE DUNK LOW DISRUPT 2 ‘MALACHITE’ ",
                            Views = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6746),
                            Description = "NIKE AIR FORCE 1 LOW BY YOU CUSTOM – GUCCI ",
                            OriginalPrice = 3950000m,
                            Price = 3950000m,
                            ReviewAverage = 0m,
                            Title = "NIKE AIR FORCE 1 LOW BY YOU CUSTOM – GUCCI ",
                            Views = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6749),
                            Description = "NIKE AIR FORCE 1 GS LOW WHITE PINK FOAM ",
                            OriginalPrice = 2950000m,
                            Price = 2950000m,
                            ReviewAverage = 0m,
                            Title = "NIKE AIR FORCE 1 GS LOW WHITE PINK FOAM ",
                            Views = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6750),
                            Description = "NIKE AIR FORCE 1 GS WHITE UNIVERSITY RED ",
                            OriginalPrice = 2850000m,
                            Price = 2850000m,
                            ReviewAverage = 0m,
                            Title = "NIKE AIR FORCE 1 GS WHITE UNIVERSITY RED ",
                            Views = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            CheckoutCount = 0,
                            DateCreated = new DateTime(2022, 10, 28, 19, 21, 1, 947, DateTimeKind.Local).AddTicks(6752),
                            Description = "NIKE AIR FORCE 1 LOW ’07 ESSENTIAL WHITE METALLIC SILVER BLACK ",
                            OriginalPrice = 3200000m,
                            Price = 3200000m,
                            ReviewAverage = 0m,
                            Title = "NIKE AIR FORCE 1 LOW ’07 ESSENTIAL WHITE METALLIC SILVER BLACK ",
                            Views = 0
                        });
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.ProductColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Red"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Green"
                        });
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.ProductInCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 11
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 13
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 14
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 15
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 16
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 17
                        });
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.ProductQuantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductQuantities");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Size = 38
                        },
                        new
                        {
                            Id = 2,
                            Size = 39
                        },
                        new
                        {
                            Id = 3,
                            Size = 40
                        });
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoPoy.Shared.Dto.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Cart", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoPoy.Shared.Dto.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoPoy.Shared.Dto.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Chat", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoPoy.Shared.Dto.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Notification", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Order", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoPoy.Shared.Dto.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.OrderDetails", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderIdFromOrder")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoPoy.Shared.Dto.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.ProductImage", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.ProductInCategory", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.Category", "Category")
                        .WithMany("ProductInCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoPoy.Shared.Dto.Product", "Product")
                        .WithMany("ProductInCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.ProductQuantity", b =>
                {
                    b.HasOne("PoPoy.Shared.Dto.ProductColor", "Color")
                        .WithMany("ProductQuantities")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoPoy.Shared.Dto.Product", "Product")
                        .WithMany("ProductQuantities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoPoy.Shared.Dto.ProductSize", "Size")
                        .WithMany("ProductQuantities")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Category", b =>
                {
                    b.Navigation("ProductInCategories");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductInCategories");

                    b.Navigation("ProductQuantities");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.ProductColor", b =>
                {
                    b.Navigation("ProductQuantities");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.ProductSize", b =>
                {
                    b.Navigation("ProductQuantities");
                });

            modelBuilder.Entity("PoPoy.Shared.Dto.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
